language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - jdk_switcher use oraclejdk8
  - java -version

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

script:
  - ulimit -a
  - mvn test
